// Auto-generated by syncIconsFromMetaobjects.ts
const DEFAULT_ICON_URL = 'https://cdn.shopify.com/s/files/1/.../default-icon.svg';

export const ICONS: Record<string,string> = {
  "boat-decals-niagara": "/cdn/shop/files/default-hero.jpg",
  "storefront-decals-hamilton": "/cdn/shop/files/default-hero.jpg",
  "waterproof-labels-niagara": "/cdn/shop/files/default-hero.jpg",
  "cannabis-labels-canada": "/cdn/shop/files/default-hero.jpg",
  "wedding-signs-niagara": "/cdn/shop/files/default-hero.jpg",
  "car-magnets-ontario": "/cdn/shop/files/default-hero.jpg",
  "bulk-yard-signs-niagara": "/cdn/shop/files/default-hero.jpg",
  "rv-graphics-ontario": "/cdn/shop/files/default-hero.jpg",
  "pet-memorial-stickers": "/cdn/shop/files/default-hero.jpg",
  "storefront-decals-st-catharines": "/cdn/shop/files/default-hero.jpg",
  "tote-bags-custom-design": "/cdn/shop/files/default-hero.jpg",
  "decals-for-small-business": "/cdn/shop/files/default-hero.jpg",
  "funny-stickers-canada": "/cdn/shop/files/default-hero.jpg",
  "laptop-stickers-artist": "/cdn/shop/files/default-hero.jpg",
  "ai-generated-decals": "/cdn/shop/files/default-hero.jpg",
  "free-svg-canada": "/cdn/shop/files/default-hero.jpg",
  "overland-vehicle-decals": "/cdn/shop/files/default-hero.jpg",
  "business-labels-ontario": "/cdn/shop/files/default-hero.jpg",
  "reflective-boat-numbers": "/cdn/shop/files/default-hero.jpg",
  "metallic-boat-decals": "/cdn/shop/files/default-hero.jpg",
  "nfc-review-stickers": "/cdn/shop/files/default-hero.jpg",
  "custom-banner-niagara": "/cdn/shop/files/default-hero.jpg",
  "funny-signs-home-decor": "/cdn/shop/files/default-hero.jpg",
  "patriotic-decals-canada": "/cdn/shop/files/default-hero.jpg",
  "svg-bundle-download": "/cdn/shop/files/default-hero.jpg",
  "plane-tail-numbers": "/cdn/shop/files/default-hero.jpg",
  "cannabis-labels-niagara": "/cdn/shop/files/default-hero.jpg",
  "waterproof-stickers-niagara": "/cdn/shop/files/default-hero.jpg",
  "branding-labels-craft-products": "/cdn/shop/files/default-hero.jpg",
  "car-magnets-bulk-order": "/cdn/shop/files/default-hero.jpg",
  "storefront-decals-toronto": "/cdn/shop/files/default-hero.jpg",
  "featured-products-1": "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/d8e7748a6d2bc4f2dfcf669f6440b0a8.jpg?v=1743238088",
  "sticker-collection": "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/14ba5f7b686e6271e9b229d13db09926.png?v=1743292248",
  "laptop-stickers": "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/724c1276f39181640d0d6fc160de74bf.png?v=1743292221",
  "disney-decals": "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/Disney_Vinyl_Decals_Collection_Small_9132818d-e28e-4016-851d-21ba28ea8dc6.jpg?v=1744183748",
  "automotive-decals": "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/Collection_Banner.png?v=1744270764",
  "brand-decals": "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/Collection_Banner_766a9a59-acc5-4586-9f56-48d46c0fbf86.png?v=1744271331",
  "full-partial-wraps": "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/custom-vinyl-decals-collection-premium-car-stickers-laptop-wall-truck-labels.png?v=1744288193",
  "boat-decals-graphics-1": "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/Selection_of_custom_vinyl_boat_decals_including_boat_name_lettering_and_graphics_on_marine-grade_material_Small_e6fc5583-4f6c-4cbe-8ecb-d8361af7ec7f.jpg?v=1744241348",
  "registration-numbers-ontario-compliant": "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/Examples_of_Ontario_compliant_boat_registration_number_decals_in_various_fonts_and_colours_Small_aa08597e-3da0-497d-bda9-57dcf53fcc98.jpg?v=1744241302",
  "custom-decals": "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/Assortment_of_custom-designed_vinyl_decals_showcasing_various_shapes_colours_and_applications.png?v=1744241326",
  "custom-stickers": "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/custom-vinyl-stickers-product-packaging-branding-laptop-decoration_Small_1eae3e7d-18f2-4b3a-8f96-e139fd518d41.jpg?v=1744241224",
  "laptop-stickers-1": "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/funny-aesthetic-vinyl-stickers-on-laptop-lids-custom-decal-designs_Small_40d2e70a-9f76-498d-923a-32f00b6caea6.jpg?v=1744241122",
  "rv-trailer-graphics": "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/RV-and-travel-trailer_Small_a532e775-4308-415b-8de6-70a4939ea213.jpg?v=1744240952",
  "storefront-decals": "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/storefront-window-vinyl-decals-business-logo-hours-promotions_Small_5b0ac8e2-aeb6-49fd-aaf5-8976192ea5bc.jpg?v=1744240926",
  "commercial-vehicle": "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/Company_van_featuring_a_full_vinyl_wrap_Small_4a232e84-3fc1-461b-ad64-e970487371a3.jpg?v=1744240898",
  "waterproof-stickers-1": "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/Waterproof_Stickers_Small_eb78f61f-9620-4a8b-ac28-6206dcef59a4.jpg?v=1744288034",
  // Static asset overrides
  "textures-concrete": "https://niagarastandsout.ca/media/textures/concrete.jpg",
  "textures-grunge-texture": "https://niagarastandsout.ca/media/textures/grunge-texture.png",
  "etsy": "https://niagarastandsout.ca/media/logos/etsy.svg",
  "facebook": "https://niagarastandsout.ca/media/logos/facebook.svg",
  "niagara-this-week": "https://niagarastandsout.ca/media/logos/niagara-this-week.svg",
  "default-hero": "https://niagarastandsout.ca/cdn/shop/files/default-hero.jpg",
  "testimonials-base": "https://niagarastandsout.ca/media/testimonials/",
  "default": DEFAULT_ICON_URL
};

export const CDN_BY_TYPE: Record<'product'|'collection'|'page', Record<string,string>> = {
  product: {},
  collection: {},
  page: {},
};

/**
 * Returns the best image URL for a given slug and type, falling back to default.
 */
export function getImageForSlug(
  slug: string,
  type: 'product' | 'collection' | 'page' = 'page'
): string {
  return (
    ICONS[slug] ||
    (CDN_BY_TYPE[type] && CDN_BY_TYPE[type][slug]) ||
    ICONS.default
  );
}
