// Auto-generated by syncIconsFromMetaobjects.ts
const DEFAULT_ICON_URL = 'https://cdn.shopify.com/s/files/1/.../default-icon.svg';



export interface IconMeta {
  title: string;
  caption: string;
  hover: string;
}

export const ICONS: Record<string, IconMeta> = {
  "boat-decals-niagara": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "storefront-decals-hamilton": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "waterproof-labels-niagara": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "cannabis-labels-canada": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "wedding-signs-niagara": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "car-magnets-ontario": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "bulk-yard-signs-niagara": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "rv-graphics-ontario": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "pet-memorial-stickers": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "storefront-decals-st-catharines": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "tote-bags-custom-design": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "decals-for-small-business": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "funny-stickers-canada": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "laptop-stickers-artist": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "ai-generated-decals": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "free-svg-canada": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "overland-vehicle-decals": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "business-labels-ontario": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "reflective-boat-numbers": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "metallic-boat-decals": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "nfc-review-stickers": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "custom-banner-niagara": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "funny-signs-home-decor": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "patriotic-decals-canada": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "svg-bundle-download": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "plane-tail-numbers": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "cannabis-labels-niagara": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "waterproof-stickers-niagara": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "branding-labels-craft-products": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "car-magnets-bulk-order": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "storefront-decals-toronto": { title: "/cdn/shop/files/default-hero.jpg", caption: "/cdn/shop/files/default-hero.jpg", hover: "" },
  "featured-products-1": { title: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/d8e7748a6d2bc4f2dfcf669f6440b0a8.jpg?v=1743238088", caption: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/d8e7748a6d2bc4f2dfcf669f6440b0a8.jpg?v=1743238088", hover: "" },
  "sticker-collection": { title: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/14ba5f7b686e6271e9b229d13db09926.png?v=1743292248", caption: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/14ba5f7b686e6271e9b229d13db09926.png?v=1743292248", hover: "" },
  "laptop-stickers": { title: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/724c1276f39181640d0d6fc160de74bf.png?v=1743292221", caption: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/724c1276f39181640d0d6fc160de74bf.png?v=1743292221", hover: "" },
  "disney-decals": { title: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/Disney_Vinyl_Decals_Collection_Small_9132818d-e28e-4016-851d-21ba28ea8dc6.jpg?v=1744183748", caption: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/Disney_Vinyl_Decals_Collection_Small_9132818d-e28e-4016-851d-21ba28ea8dc6.jpg?v=1744183748", hover: "" },
  "automotive-decals": { title: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/Collection_Banner.png?v=1744270764", caption: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/Collection_Banner.png?v=1744270764", hover: "" },
  "brand-decals": { title: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/Collection_Banner_766a9a59-acc5-4586-9f56-48d46c0fbf86.png?v=1744271331", caption: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/Collection_Banner_766a9a59-acc5-4586-9f56-48d46c0fbf86.png?v=1744271331", hover: "" },
  "full-partial-wraps": { title: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/custom-vinyl-decals-collection-premium-car-stickers-laptop-wall-truck-labels.png?v=1744288193", caption: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/custom-vinyl-decals-collection-premium-car-stickers-laptop-wall-truck-labels.png?v=1744288193", hover: "" },
  "boat-decals-graphics-1": { title: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/Selection_of_custom_vinyl_boat_decals_including_boat_name_lettering_and_graphics_on_marine-grade_material_Small_e6fc5583-4f6c-4cbe-8ecb-d8361af7ec7f.jpg?v=1744241348", caption: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/Selection_of_custom_vinyl_boat_decals_including_boat_name_lettering_and_graphics_on_marine-grade_material_Small_e6fc5583-4f6c-4cbe-8ecb-d8361af7ec7f.jpg?v=1744241348", hover: "" },
  "registration-numbers-ontario-compliant": { title: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/Examples_of_Ontario_compliant_boat_registration_number_decals_in_various_fonts_and_colours_Small_aa08597e-3da0-497d-bda9-57dcf53fcc98.jpg?v=1744241302", caption: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/Examples_of_Ontario_compliant_boat_registration_number_decals_in_various_fonts_and_colours_Small_aa08597e-3da0-497d-bda9-57dcf53fcc98.jpg?v=1744241302", hover: "" },
  "custom-decals": { title: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/Assortment_of_custom-designed_vinyl_decals_showcasing_various_shapes_colours_and_applications.png?v=1744241326", caption: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/Assortment_of_custom-designed_vinyl_decals_showcasing_various_shapes_colours_and_applications.png?v=1744241326", hover: "" },
  "custom-stickers": { title: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/custom-vinyl-stickers-product-packaging-branding-laptop-decoration_Small_1eae3e7d-18f2-4b3a-8f96-e139fd518d41.jpg?v=1744241224", caption: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/custom-vinyl-stickers-product-packaging-branding-laptop-decoration_Small_1eae3e7d-18f2-4b3a-8f96-e139fd518d41.jpg?v=1744241224", hover: "" },
  "laptop-stickers-1": { title: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/funny-aesthetic-vinyl-stickers-on-laptop-lids-custom-decal-designs_Small_40d2e70a-9f76-498d-923a-32f00b6caea6.jpg?v=1744241122", caption: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/funny-aesthetic-vinyl-stickers-on-laptop-lids-custom-decal-designs_Small_40d2e70a-9f76-498d-923a-32f00b6caea6.jpg?v=1744241122", hover: "" },
  "rv-trailer-graphics": { title: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/RV-and-travel-trailer_Small_a532e775-4308-415b-8de6-70a4939ea213.jpg?v=1744240952", caption: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/RV-and-travel-trailer_Small_a532e775-4308-415b-8de6-70a4939ea213.jpg?v=1744240952", hover: "" },
  "storefront-decals": { title: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/storefront-window-vinyl-decals-business-logo-hours-promotions_Small_5b0ac8e2-aeb6-49fd-aaf5-8976192ea5bc.jpg?v=1744240926", caption: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/storefront-window-vinyl-decals-business-logo-hours-promotions_Small_5b0ac8e2-aeb6-49fd-aaf5-8976192ea5bc.jpg?v=1744240926", hover: "" },
  "commercial-vehicle": { title: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/Company_van_featuring_a_full_vinyl_wrap_Small_4a232e84-3fc1-461b-ad64-e970487371a3.jpg?v=1744240898", caption: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/Company_van_featuring_a_full_vinyl_wrap_Small_4a232e84-3fc1-461b-ad64-e970487371a3.jpg?v=1744240898", hover: "" },
  "waterproof-stickers-1": { title: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/Waterproof_Stickers_Small_eb78f61f-9620-4a8b-ac28-6206dcef59a4.jpg?v=1744288034", caption: "https://cdn.shopify.com/s/files/1/0748/9824/3835/collections/Waterproof_Stickers_Small_eb78f61f-9620-4a8b-ac28-6206dcef59a4.jpg?v=1744288034", hover: "" },
  // Static asset overrides
  "textures-concrete": { title: "https://niagarastandsout.ca/media/textures/concrete.jpg", caption: "https://niagarastandsout.ca/media/textures/concrete.jpg", hover: "" },
  "textures-grunge-texture": { title: "https://niagarastandsout.ca/media/textures/grunge-texture.png", caption: "https://niagarastandsout.ca/media/textures/grunge-texture.png", hover: "" },
  "etsy": { title: "https://niagarastandsout.ca/media/logos/etsy.svg", caption: "https://niagarastandsout.ca/media/logos/etsy.svg", hover: "" },
  "facebook": { title: "https://niagarastandsout.ca/media/logos/facebook.svg", caption: "https://niagarastandsout.ca/media/logos/facebook.svg", hover: "" },
  "niagara-this-week": { title: "https://niagarastandsout.ca/media/logos/niagara-this-week.svg", caption: "https://niagarastandsout.ca/media/logos/niagara-this-week.svg", hover: "" },
  "default-hero": { title: "https://niagarastandsout.ca/cdn/shop/files/default-hero.jpg", caption: "https://niagarastandsout.ca/cdn/shop/files/default-hero.jpg", hover: "" },
  "testimonials-base": { title: "https://niagarastandsout.ca/media/testimonials/", caption: "https://niagarastandsout.ca/media/testimonials/", hover: "" },
  "default": { title: DEFAULT_ICON_URL, caption: DEFAULT_ICON_URL, hover: "" }
};

export const CDN_BY_TYPE: Record<'product'|'collection'|'page', Record<string, IconMeta>> = {
  product: {},
  collection: {},
  page: {},
};

/**
 * Returns the best image URL for a given slug and type, falling back to default.
 */
export function getImageForSlug(
  slug: string,
  type: 'product' | 'collection' | 'page' = 'page'
): string {
  return (
    ICONS[slug]?.title ||
    CDN_BY_TYPE[type][slug]?.title ||
    ICONS.default.title
  );
}
