// Auto-generated by generateImageMeta.ts
export const IMAGE_META = {
  "boat-decals-niagara": {
    "title": "Custom Boat Decals in Niagara",
    "caption": "Custom Boat Decals in Niagara delivered to Niagara Falls",
    "hover": "Shop Custom Boat Decals in Niagara"
  },
  "storefront-decals-hamilton": {
    "title": "Storefront Window Decals for Hamilton Shops",
    "caption": "Storefront Window Decals for Hamilton Shops delivered to St. Catharines",
    "hover": "Shop Storefront Window Decals for Hamilton Shops"
  },
  "waterproof-labels-niagara": {
    "title": "Waterproof Labels for Niagara Businesses",
    "caption": "Waterproof Labels for Niagara Businesses delivered to Hamilton",
    "hover": "Shop Waterproof Labels for Niagara Businesses"
  },
  "cannabis-labels-canada": {
    "title": "Legal Cannabis Stickers & Packaging Labels",
    "caption": "Legal Cannabis Stickers & Packaging Labels delivered to Fort Erie",
    "hover": "Shop Legal Cannabis Stickers & Packaging Labels"
  },
  "wedding-signs-niagara": {
    "title": "Custom Wedding Welcome Signs in Niagara",
    "caption": "Custom Wedding Welcome Signs in Niagara delivered to Niagara Falls",
    "hover": "Shop Custom Wedding Welcome Signs in Niagara"
  },
  "car-magnets-ontario": {
    "title": "Ontario’s Custom Car Magnet Printing",
    "caption": "Ontario’s Custom Car Magnet Printing delivered to St. Catharines",
    "hover": "Shop Ontario’s Custom Car Magnet Printing"
  },
  "bulk-yard-signs-niagara": {
    "title": "Bulk Custom Yard Signs – Fast Niagara Printing",
    "caption": "Bulk Custom Yard Signs – Fast Niagara Printing delivered to Hamilton",
    "hover": "Shop Bulk Custom Yard Signs – Fast Niagara Printing"
  },
  "rv-graphics-ontario": {
    "title": "RV + Trailer Decals Across Ontario",
    "caption": "RV + Trailer Decals Across Ontario delivered to Fort Erie",
    "hover": "Shop RV + Trailer Decals Across Ontario"
  },
  "pet-memorial-stickers": {
    "title": "Personalized Pet Memorial Decals (Canada)",
    "caption": "Personalized Pet Memorial Decals (Canada) delivered to Niagara Falls",
    "hover": "Shop Personalized Pet Memorial Decals (Canada)"
  },
  "storefront-decals-st-catharines": {
    "title": "Vinyl Window Decals for St. Catharines",
    "caption": "Vinyl Window Decals for St. Catharines delivered to St. Catharines",
    "hover": "Shop Vinyl Window Decals for St. Catharines"
  },
  "tote-bags-custom-design": {
    "title": "Custom Design Tote Bags Printed Locally",
    "caption": "Custom Design Tote Bags Printed Locally delivered to Hamilton",
    "hover": "Shop Custom Design Tote Bags Printed Locally"
  },
  "decals-for-small-business": {
    "title": "Decals for Small Businesses (Local Printing)",
    "caption": "Decals for Small Businesses (Local Printing) delivered to Fort Erie",
    "hover": "Shop Decals for Small Businesses (Local Printing)"
  },
  "funny-stickers-canada": {
    "title": "Funny Vinyl Stickers Made in Canada",
    "caption": "Funny Vinyl Stickers Made in Canada delivered to Niagara Falls",
    "hover": "Shop Funny Vinyl Stickers Made in Canada"
  },
  "laptop-stickers-artist": {
    "title": "Custom Laptop Stickers for Designers",
    "caption": "Custom Laptop Stickers for Designers delivered to St. Catharines",
    "hover": "Shop Custom Laptop Stickers for Designers"
  },
  "ai-generated-decals": {
    "title": "AI-Generated Stickers from Your Prompts",
    "caption": "AI-Generated Stickers from Your Prompts delivered to Hamilton",
    "hover": "Shop AI-Generated Stickers from Your Prompts"
  },
  "free-svg-canada": {
    "title": "Free SVG Files for Cutting in Canada",
    "caption": "Free SVG Files for Cutting in Canada delivered to Fort Erie",
    "hover": "Shop Free SVG Files for Cutting in Canada"
  },
  "overland-vehicle-decals": {
    "title": "National Park + Adventure Decals",
    "caption": "National Park + Adventure Decals delivered to Niagara Falls",
    "hover": "Shop National Park + Adventure Decals"
  },
  "business-labels-ontario": {
    "title": "Branded Business Labels – Ontario Print Shop",
    "caption": "Branded Business Labels – Ontario Print Shop delivered to St. Catharines",
    "hover": "Shop Branded Business Labels – Ontario Print Shop"
  },
  "reflective-boat-numbers": {
    "title": "Transport Canada Reflective Boat Numbers",
    "caption": "Transport Canada Reflective Boat Numbers delivered to Hamilton",
    "hover": "Shop Transport Canada Reflective Boat Numbers"
  },
  "metallic-boat-decals": {
    "title": "Premium Metallic Boat Name Decals",
    "caption": "Premium Metallic Boat Name Decals delivered to Fort Erie",
    "hover": "Shop Premium Metallic Boat Name Decals"
  },
  "nfc-review-stickers": {
    "title": "NFC Stickers to Get More Google Reviews",
    "caption": "NFC Stickers to Get More Google Reviews delivered to Niagara Falls",
    "hover": "Shop NFC Stickers to Get More Google Reviews"
  },
  "custom-banner-niagara": {
    "title": "Custom Event Banners – Niagara Region",
    "caption": "Custom Event Banners – Niagara Region delivered to St. Catharines",
    "hover": "Shop Custom Event Banners – Niagara Region"
  },
  "funny-signs-home-decor": {
    "title": "Funny Signs for Your Kitchen & Man Cave",
    "caption": "Funny Signs for Your Kitchen & Man Cave delivered to Hamilton",
    "hover": "Shop Funny Signs for Your Kitchen & Man Cave"
  },
  "patriotic-decals-canada": {
    "title": "Canadian Flag + Military Pride Decals",
    "caption": "Canadian Flag + Military Pride Decals delivered to Fort Erie",
    "hover": "Shop Canadian Flag + Military Pride Decals"
  },
  "svg-bundle-download": {
    "title": "Urban SVG Cut File Bundles (Free & Paid)",
    "caption": "Urban SVG Cut File Bundles (Free & Paid) delivered to Niagara Falls",
    "hover": "Shop Urban SVG Cut File Bundles (Free & Paid)"
  },
  "plane-tail-numbers": {
    "title": "Aircraft Tail Numbers + Lettering Kits",
    "caption": "Aircraft Tail Numbers + Lettering Kits delivered to St. Catharines",
    "hover": "Shop Aircraft Tail Numbers + Lettering Kits"
  },
  "cannabis-labels-niagara": {
    "title": "Local Niagara Cannabis Product Labels",
    "caption": "Local Niagara Cannabis Product Labels delivered to Hamilton",
    "hover": "Shop Local Niagara Cannabis Product Labels"
  },
  "waterproof-stickers-niagara": {
    "title": "Waterproof Custom Stickers (Fast Turnaround)",
    "caption": "Waterproof Custom Stickers (Fast Turnaround) delivered to Fort Erie",
    "hover": "Shop Waterproof Custom Stickers (Fast Turnaround)"
  },
  "branding-labels-craft-products": {
    "title": "Labels for Candles, Jars, Packaging",
    "caption": "Labels for Candles, Jars, Packaging delivered to Niagara Falls",
    "hover": "Shop Labels for Candles, Jars, Packaging"
  },
  "car-magnets-bulk-order": {
    "title": "Car Magnets Bulk Order Deal – Free Shipping",
    "caption": "Car Magnets Bulk Order Deal – Free Shipping delivered to St. Catharines",
    "hover": "Shop Car Magnets Bulk Order Deal – Free Shipping"
  },
  "storefront-decals-toronto": {
    "title": "Toronto Storefront Decals – Delivered Fast",
    "caption": "Toronto Storefront Decals – Delivered Fast delivered to Hamilton",
    "hover": "Shop Toronto Storefront Decals – Delivered Fast"
  },
  "default": {
    "title": "Default Image",
    "caption": "",
    "hover": "Learn More"
  }
};
