#!/usr/bin/env tsx
import fs from 'fs';
import path from 'path';
import seoPages from '../data/seo-pages.json';
import { getAllCollections } from '../lib/shopify';

async function main() {
  const meta: Record<string, { title: string; caption: string; hover: string }> = {};

  // SEO page metadata
  for (const p of seoPages) {
    meta[p.slug] = {
      title: p.title,
      caption: p.subtitle,
      hover: p.cta,
    };
  }

  // Collection metadata
  const cols = await getAllCollections();
  for (const col of cols) {
    meta[col.handle] = {
      title: col.title,
      caption: col.description || '',
      hover: 'Shop Now',
    };
  }

  // Default fallback
  meta['default'] = { title: 'Default Image', caption: '', hover: 'Learn More' };

  const outPath = path.resolve(__dirname, '../lib/imageMeta.ts');
  const content = `// Auto-generated by generateImageMeta.ts\nexport const IMAGE_META = ${JSON.stringify(meta, null, 2)};\n`;
  fs.writeFileSync(outPath, content);
  console.log('✅ lib/imageMeta.ts updated with IMAGE_META entries');
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
